[package]
name = "hello_opencv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.80.0"
chrono = "0.4.24"
surrealdb = "1.0.0-beta.9"
